name: Upload to Maven Central

on:
    workflow_dispatch:
        inputs:
            bundle_path:
                description: 'Path to central-bundle.zip'
                required: false
                default: 'build/central-bundle.zip'
                type: string

jobs:
    upload-central:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Set up JDK 22
                uses: actions/setup-java@v4
                with:
                    java-version: '22'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Build and create bundle
                run: |
                    ./gradlew build
            -   name: Upload bundle to Maven Central
                env:
                    CENTRAL_TOKEN_USER: ${{ secrets.CENTRAL_TOKEN_USER }}
                    CENTRAL_TOKEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
                    BUNDLE_PATH: ${{ github.event.inputs.bundle_path || 'build/central-bundle.zip' }}
                run: |
                    if [ ! -f "$BUNDLE_PATH" ]; then
                      echo "ERROR: Bundle not found at $BUNDLE_PATH"
                      exit 1
                    fi
                    
                    TOKEN=$(printf "%s:%s" "$CENTRAL_TOKEN_USER" "$CENTRAL_TOKEN_PASSWORD" | base64)
                    echo "Uploading bundle to Maven Central..."
                    
                    curl --fail --show-error --request POST \
                      --header "Authorization: Bearer $TOKEN" \
                      --form bundle=@"$BUNDLE_PATH" \
                      https://central.sonatype.com/api/v1/publisher/upload