name: Release and Publish

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  release:
    uses: ImBit/bit-build/.github/workflows/publish.yml@main
    with:
      modules: "."
    secrets: inherit